name: Java CI

on:
  push:
    branches:
      - main
      - ramu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: List files in the directory
        run: ls -la ./OrangeHRM/orangehrm-test

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver (Hardcoded Versions)
        run: |
          CHROME_VERSION=117
          DRIVER_VERSION=117.0.5938.92
          echo "Using Chrome Version: $CHROME_VERSION and Driver Version: $DRIVER_VERSION"
          curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver


      - name: Build with Maven
        run: mvn clean install
        working-directory: ./OrangeHRM/orangehrm-test

      - name: Run TestNG tests using testng.xml
        working-directory: ./OrangeHRM/orangehrm-test
        run: mvn test -DsuiteXmlFile=testng.xml

      - uses: actions/upload-artifact@v3
        if: always()
        with:
            name: Report
            path: test-results
            retention-days: 2

