name: Java CI

on:
  push:
    branches:
      - main
      - ramu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: List files in the directory
        run: ls -la ./OrangeHRM/orangehrm-test

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          version: 131.0.6778.139 


      - name: Build with Maven
        run: mvn clean install
        working-directory: ./OrangeHRM/orangehrm-test

      - name: Run TestNG tests using testng.xml
        working-directory: ./OrangeHRM/orangehrm-test
        run: mvn test -DsuiteXmlFile=testng.xml

      - uses: actions/upload-artifact@v3
        if: always()
        with:
            name: Report
            path: test-results
            retention-days: 2

