name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget unzip

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          # Get the major version of Chrome
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION"
          
          # Get the ChromeDriver version that corresponds to the major version of Chrome
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)

          # If the version is not found, fall back to the latest ChromeDriver
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Unable to find ChromeDriver for Chrome version $CHROME_VERSION. Falling back to the latest version."
            DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi

          # If still no version, exit with error
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Error: Could not determine a valid ChromeDriver version."
            exit 1
          fi

          echo "Using ChromeDriver version: $DRIVER_VERSION"

          # Download the ChromeDriver version
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip

          # Unzip the driver and move it to the appropriate directory
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver

          # Verify ChromeDriver installation
          chromedriver --version

      - name: List files in the directory
        run: ls -la ./OrangeHRM/orangehrm-test

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./OrangeHRM/orangehrm-test

      - name: Run TestNG tests using testng.xml
        working-directory: ./OrangeHRM/orangehrm-test
        run: mvn test -DsuiteXmlFile=src/test/resources/testng.xml

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Report
          path: test-results
          retention-days: 2
