name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Specify the Java distribution (e.g., adoptopenjdk, temurin)
          java-version: '23'  # Specify your Java version
      - name: List files in the directory
        run: ls -la ./OrangeHRM/orangehrm-test

      - name: Build with Maven
        working-directory: ProjectReoprtOrangeHRM/OrangeHRM/orangehrm-test/pom.xml
        run: mvn clean install
      - name: Run Tests
        working-directory: ./OrangeHRM/orangehrm-test
        run: mvn test

