name: Java CI

on:
  push:
    branches:
      - main
      - ramu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Run Tests with Debugging
        run: mvn test -DsuiteXmlFile=src/test/resources/testng.xml -X
        working-directory: ./OrangeHRM/orangehrm-test

      - name: Check Test Reports
        run: cat ./OrangeHRM/orangehrm-test/target/surefire-reports/*.txt
        working-directory: ./OrangeHRM/orangehrm-test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: ./OrangeHRM/orangehrm-test/target/surefire-reports
